image: Visual Studio 2017
branches:
  only:
  - master
  - develop
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - docker version
  - cinst gitversion.portable -y
before_build:
  - nuget restore
  - ps: $env:VERSION=$(gitversion /showvariable NuGetVersionV2)
  - ps: $env:TEST_VERSION=$(gitversion /showvariable MajorMinorPatch)
build_script:
  - ps: dotnet restore
  - ps: cd src/dotnet-setversion; dotnet setversion $env:VERSION; dotnet pack -c Release -o release/; cd ../..
test_script:
  - ps: cd src/dotnet-setversion; dotnet setversion $env:TEST_VERSION; cd ../..
  - ps: test/e2e.ps1
artifacts:
  path: src/dotnet-setversion/release/*.nupkg
  name: NuGet packages
deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: USCwZe1eILJaDmG30VFhlFWmr2P0G6o0HhUau72/W+TzyAMZyqEfL//vQhfjTSKP
  artifact: NuGet packages
  on:
    branch: master